### ISSUE TITLE
FrostyToolsuite didn’t launch game

### ISSUE THREAD

**Issue by shoushou1106** [p0358/Fuck_off_EA_App#1]
[FrostyToolsuite](https://github.com/CadeEvs/FrostyToolsuite) can modding games running on Frostbite.
My friend can't use Frosty launch game after installation. None of my four friends have succeeded.
One of Origin will be killed.
The other one didn’t start game.
No any log.

One person successfully started Origin and Frosty work well. He urged me to tell you his method to provide research.(He didn’t install Fuck_off_EA_App)

Set to lock, unreadable `%localappdata%\Origin`
Delete EA installer in `(Game Folder)\__Installer\Origin\redist\`
Delete `%appdata%\Origin`
Copy `%appdata%\Origin` in 2019 and Paste to `%appdata%\`
Edit eacore：
```
[connection]
EnvironmentName=production
[Feature]
CdnOverride=akamai
```

you can check [Video](https://www.bilibili.com/video/BV1aV4y1y7o1/)
ZQ find this way at UTC+8 2023-06-24 00:56:00

**Comment by shoushou1106** [comment]
None of my four friends have succeeded.

**Comment by p0358** [comment]
> My friend can't use Frosty launch game after installation.
But are they able to launch the games directly from Origin?

> One of Origin will be killed.
What Origin version do they have? I only tested on 10.5.119 and 10.5.122, though I tried to generally ensure that if some hook/patch cannot be made, that it'd show a message box instead of failing silently... Do they perhaps have any crash reports in `%localappdata%\CrashDumps`?

Also if you previously used the patch from someone else that involved replacing two exe files and one dll (Origin.exe, OriginClient.dll and OriginClientService.dll), then you should reinstall Origin first, as that patch was actually screwing with some Origin's features.

But generally it's a bit odd, since my patch itself shouldn't interfere too much with how Origin and its operations normally work. I'm wondering if it could be some issue with FrostyToolsuite, if for example running the games directly would turn out to work just fine?

**Comment by p0358** [comment]
Try again now with v2 release

**Comment by GTechene** [comment]
I confirm it's working fine on my end with latest Origin (10.5.122.52971), Frosty Mod Manager 1.0.6.2 and v2 of this patch when trying to launch Mass Effect : Andromeda from Frosty. It did not work with patch v1.

Thank you ! 👍

**Comment by shoushou1106** [comment]
v2 works
Thank you!

**Comment by shoushou1106** [comment]
AGAIN!!! Never use ZQ's method, use v2
