### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Zerogoki00** [p0358/Fuck_off_EA_App#59]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

I have this patch installed but today Origin started to tell me to update...
![Снимок экрана 2024-08-07 010651](https://github.com/user-attachments/assets/229e2cd2-941e-46a8-81ee-d09d7a05c07d)

**Comment by p0358** [comment]
On the latest version of the patch? It shouldn't be happening since nothing changed on this update page: https://api1.origin.com/autopatch/2/upgradeFrom/10.5.119.52718/pl_PL/PROD?platform=PCWIN&osVersion=10.0.19045&servicePackVersion=0.0&priority=2

Fake version update to 12.x should be blocked by the latest patch version. So make sure it didn't get uninstalled or something accidentally. Alternatively you can also use the method from README to disable updated by editing the .ini file in Origin installation dir...

**Comment by BenjaOliva** [comment]
Just tried and facing same issue.

- Tried modifying the `.ini` file
- Tried dropping the version.dll file on the folder
- Initially tried with the .exe patch installer

**Comment by calluna** [comment]
Yep same... tried all the manual steps and it is still launching the updater.
I am also trying to install the FU exe with bottles but when picking an install path and browsing to the Origin folder it keeps telling me to use a full path with C, but that's not possible on Linux, because it is not in the C folder, it is in the compat folder drive_c

**Comment by Zerogoki00** [comment]
It works again after complete reinstall

**Comment by j0p3s** [comment]
Close this since its not an issue
