### ISSUE TITLE
not working :<

### ISSUE THREAD

**Issue by Evolu7ioN** [p0358/Fuck_off_EA_App#61]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

not working now...sad4this:[
may u fix that?i will be grateful
![20240927163930](https://github.com/user-attachments/assets/33e494ed-24ae-4713-87c1-59f12b756791)

**Comment by Pierreluc18** [comment]
still work without issue likely you need to delete origin and reinstall it and use Fuck_off_EA_App_installer
![Origin](https://github.com/user-attachments/assets/5417ecfa-89e4-4307-8804-a5f7317ac001)

**Comment by p0358** [comment]
As said above, it still works. Just close off all Origin processes and install the patch again.

**Comment by Evolu7ioN** [comment]
install the patch again didn't fix it but i read the readme again and add
[Bootstrap]
EnableUpdating=false
in eacore.ini
that fixed it.
sorry for my careless :< and thank u for ur reply
have a nice day bro ur my hero   u save my origin :>

**Comment by p0358** [comment]
It's honestly still kinda weird, because it's supposed to suppress broken updates even despite no update disablement in EACore.ini. I'm curious where it launched OriginThinSetup.exe from. If it's not a matter of missing `version.dll`, it's possible there was a cached update downloaded and it'd launch its installer (in a different directory). That installer in turn would clear up Origin install dir and erase `version.dll` too... (with that said, currently there should be no cached updated, since Origin only provides broken update info in the API since some time ago...)

**Comment by Evolu7ioN** [comment]
idk bro,it still working but is weird tho.
when i start games from origin everything is okay but when i start games from steam origin will stop me immediately and tell me that u can't start games without using eaapp,u need a update.
