### ISSUE TITLE
Facing this from today 

### ISSUE THREAD

**Issue by Eryx21** [p0358/Fuck_off_EA_App#62]
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue
![image](https://github.com/user-attachments/assets/3640b820-5abc-4c6a-a841-6aa31206bc8b)

**Comment by 1AGRESSOR** [comment]
+1

**Comment by p0358** [comment]
It seems that all requests to `https://api.origin.com/ecommerce2/` subpath are returning error 503 with a generic message. Well, the Akamai proxy might be masking the real error and only EA would see the real error after using their tool to translate error reference ids. Either way it's something that EA most likely broke on their side.

But Origin keeps on retrying these requests all the time when it's running, so I imagine it will show up an uptick of errors on their dashboard of sorts, so all we can do is hope they'll fix it soon probably. I mean they did fix the user search endpoint before, so it's not improbable. I'm glad at least the game launching still works fine, but not being able to download games is gonna be problematic in the long run otherwise.

**Comment by p0358** [comment]
Seems like #40 all over again, hopefully will magically fix itself on its own as well

**Comment by rodrig0rm** [comment]
''Fuckeaapp'' stop working :( pleaaaase update! 


![image](https://github.com/user-attachments/assets/88d1d9de-7fcb-4116-b273-5cc612972dbc)

**Comment by GGuyX** [comment]
Does this have anything to do with The Sims 4 not launching? I'm facing the same error, but in addition to this, after last The Sims 4 update, it stopped working - It is now exiting with the following message:
Unable to start:
Error initializing start.
[135dec40:29f00e76:00000084:18a1dd51]

I have used Google Translate to translate the error from Polish but it seems accurate.

**Comment by GGuyX** [comment]
Nevermind - The error was related to (at least so I'm guessing) Windows Defender blocking Origin's access to the game.

**Comment by Eryx21** [comment]
> Seems like #40 all over again, hopefully will magically fix itself on its own as well

Yep, it's working again.

**Comment by p0358** [comment]
Yay. Glad EA is maintaining these APIs still
